### ISSUE TITLE
Create wrong alloy.jmk because of is-installed-globally doesn't work as expected on Windows 10

### ISSUE THREAD

**Issue by AhmedMSayed** [macCesar/purgeTSS#12]
When trying to use purgetss on my project on Windows 10 for the first time I faced build error ..
After some debugging I found the issue is that **is-installed-globally** package is not working as expected because it has a wrong npm globall path from **global-dirs** package
So _isInstalledGlobally_ check is not working and lead to select wrong _alloy.jmk_ path
If you can skip _isInstalledGlobally_  check or make a workaround if it doesn't work that would be great

Node  16.16.0
Ti SDk 11.0.0
Ti CLI   6.1.1

**Comment by macCesar** [comment]
Hi there.. I'll take a look!!

Thanks for reporting this bug!!

**Comment by macCesar** [comment]
To fix you issue.. please follow these steps:

- Update PurgeTSS to v5.3.15
- Delete the `alloy.jmk' file
- Run purgetss again to add the correct `child-process`

**Comment by macCesar** [comment]
We've completely remove the package `is-installed-globally`...

We will update the documentation to specify that **PurgeTSS** will only work when installed globally!!!

**Comment by AhmedMSayed** [comment]
Great it works now thanks a lot.
I agree Purgetss should installed globally because when I tried to install it on the project Dir it takes time in build

**Comment by macCesar** [comment]
I'm glad it worked out for you!!!

I'm going to close this issue now!!
