### ISSUE TITLE
"watch" command doesn't works

### ISSUE THREAD

**Issue by ottopic** [macCesar/purgeTSS#17]
Watch is enabled and purgeTSS is configured on new Alloy project.
If I add for example:

```xml
<Avatar module="tikit.ui" classes="bg-yellow-900 text-yellow-50" variant="chip" size="base" name="Mr. John Doe" image="https://randomuser.me/api/portraits/men/86.jpg" />
```

I see avatar light green, to see correct color I need to stop live and rebuild project.

**Comment by macCesar** [comment]
Here's a video showing the expected behavior when making changes in LiveView:

https://user-images.githubusercontent.com/1383124/206630708-45774698-58bd-4404-ae99-505b64d8ae28.mov

**Comment by ottopic** [comment]
In any case in the log I see executed '::PurgeTSS:: Auto-Purging '.
I will try creating new project.

**Comment by ottopic** [comment]
I tried using your sample app https://github.com/macCesar/TiKit-UI-Components and the problem is the same into two different mac. I think there is something else to investigate.

Mac OS: 13.0.1
Xcode: 14.1
VSCode: 1.73.1
Nodejs: 16.18.1
Alloy: 2.0.2
Ti SDK 11.1.1.GA
Ti CLI: 6.1.1
Purgetss: I think lastone but I don't know to check it

**Comment by macCesar** [comment]
To check the version use
```bash
> purgetss -V
6.2.16
```

Getting back to your initial issue... I sometimes don't see the changes made, until I “refresh” `app.tss` by just saving it .. **LiveView** will see the change and read the classes correctly!!

**Can you create a small video showing the code, and the issue please ??** 🙏🏻

**Comment by macCesar** [comment]
This is the output after I hit 'save' on `index.xml`
```bash
[LiveView] Alloy recompile initiated for iOS

[LiveView] Reload Triggered
  REASON: File Changed
  FILE: /Users/cesar/Developer/Apps/adam-armstrong/app/views/index.xml

[LiveView] Client disconnected
[LiveView] Alloy recompile initiated for ios
[INFO]  [LiveView] Reloading App
[INFO]  UI SHUTDOWN COMPLETE. TRYING TO RESUME RESTART
[LiveView] Client connected
[INFO]  adam-armstrong 1.0 (Powered by Titanium 11.1.1.2b4b824438)
[INFO]  Reachability Flag Status: -R ------- networkStatusForFlags
[LiveView] File changes ignored while Alloy compiling

[LiveView] Reload Triggered
  REASON: File Changed
  FILE: /Users/cesar/Developer/Apps/adam-armstrong/app/styles/app.tss

[LiveView] Client disconnected
[LiveView] Client connected
[INFO]  [LiveView] Reloading App
[INFO]  UI SHUTDOWN COMPLETE. TRYING TO RESUME RESTART
[INFO]  adam-armstrong 1.0 (Powered by Titanium 11.1.1.2b4b824438)
[INFO]  Reachability Flag Status: -R ------- networkStatusForFlags
```

**Noticed the "double" reloading?? One for `index.xml` and one for `app.tss` Both were automatically triggered..**

BUT sometimes the second reload doesn't trigger, that's were I have to “save” `app.tss` for LiveView to see the changes!!

For what I know.. PurgeTSS has nothing to do with that, that's an issue with Titanium and/or LiveView.

**Comment by ottopic** [comment]
Ok, I confirm purgetss 6.2.16
Adding new line blank into app.tss I see correctly change of bg color but so far it seems to happen all the time, not sometimes.


https://user-images.githubusercontent.com/5537554/206742792-7751f0b6-c21d-4bb5-ac0a-dc327a2fd611.mov

**Comment by ottopic** [comment]
Never I have double trigger on 2 different mac.
Do you have the same configuration?

```
Mac OS Intel: 13.0.1
Xcode: 14.1
VSCode: 1.73.1
Nodejs: 16.18.1
Alloy: 2.0.2
Ti SDK 11.1.1.GA
Ti CLI: 6.1.1
Purgetss: 6.2.16
```

**Comment by macCesar** [comment]
Thanks for that video.. 👍🏻

For what I can see, there's only one reload triggered when you save the `xml` file.. 🙁

I honestly don't know how to tell LiveView to reload a second time!!

You can see that PurgeTSS is working when you add a few lines in `app.tss` and after saving it the extra lines disappear !!! 

That's when PurgeTSS re-creates `app.tss`...

Unfortunately , LiveView ignores that when you save an xml file and `app.tss` is re-created.

**Comment by macCesar** [comment]
I have a M1 Mac mini with pretty much the same setup..
Xcode: 14.1
VSCode: 1.74.0
NodeJS: v16.18.1
NPM: 8.19.2
LiveVIew: 1.5.5
Ti: 6.1.1
Ti SDK: 11.1.1.GA

**Comment by ottopic** [comment]
How can I check liveview version?

**Comment by macCesar** [comment]
I think this has something to do with this issue:

```bash
[LiveView] File changes ignored while Alloy compiling
```

Maybe there is not enough time between the first reload from LiveView and when PurgeTSS re-creates `app.tss`..

**Comment by macCesar** [comment]
> How can I check liveview version?

```bash
liveview -V
1.5.5
```

**Comment by macCesar** [comment]
You are using the standalone version.. right ??

```bash
> npm i -g liveview
```

**Comment by ottopic** [comment]
> You are using the standalone version.. right ??

Tried to install it but never is changed :-/

**Comment by ottopic** [comment]
> I think this has something to do with this issue:
> 
> ```shell
> [LiveView] File changes ignored while Alloy compiling
> ```
> 
> Maybe there is not enough time between the first reload from LiveView and when PurgeTSS re-creates `app.tss`..


[LiveView] Alloy recompile initiated for ios
[LiveView] File changes ignored while Alloy compiling
[LiveView] Reload Triggered
  REASON: File Changed
  FILE: /Users/[USER]/Downloads/TiKit-UI-Components-master/app/views/sections/buttons.xml
[LiveView] Client disconnected
[INFO]  [LiveView] Reloading App
[INFO]  UI SHUTDOWN COMPLETE. TRYING TO RESUME RESTART
[LiveView] Client connected
[INFO]  TiKit UI Components 1.0 (Powered by Titanium 11.1.1.2b4b824438)
[INFO]  Reachability Flag Status: -R ------- networkStatusForFlags

**Comment by ottopic** [comment]
So, thanks for help, I will see if something change in future

**Comment by macCesar** [comment]
I asked on slack about LiveView !! 👍🏼 Let's see what they say!!

**Comment by macCesar** [comment]
**As always.. The simplest solution tends to be the correct one!!** :exploding_head:

I modified the function from execSync to exec in alloy.jmk, and now the Views are updating correctly!! :tada:
```javascript
task('pre:compile', function(event, logger) {
  require('child_process').exec('purgetss', logger.warn('::PurgeTSS:: Auto-Purging ' + event.dir.project));
});
```

**Please update to purgetss@6.2.18**
