### ISSUE TITLE
Class is overwritten

### ISSUE THREAD

**Issue by Mancera63** [macCesar/purgeTSS#18]
I have styles defined in my file **_app.tss** for the Window tag, but when I do some build in Purge it generates its own class for the tag and my style doesn't work.

Is there a way to exclude that it generates the style when doing the build?

**Comment by macCesar** [comment]
Hello Mancera... The Window class is automatically generate by PurgeTSS..

You can disable it.. Or even better.. add your custom values in **config.js** file.

**Comment by macCesar** [comment]
Please.. let me know If you need any help!! 😊
